version: '3.8'

services:
  database:
    image: mysql
    volumes:
      - ./src/database/:/docker-entrypoint-initdb.d/world.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=world
    ports:
      - 3306:3306

  user-database:
    image: mysql
    volumes:
      - ./src/users.sql:/docker-entrypoint-initdb.d/users.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=users
    ports:
      - 3307:3307

  web:
    build: ./src
    volumes:
      - ./src:/app
    depends_on:
      - database
    restart: on-failure
    command: supervisor -e '.' app.js
    environment:
      - DATABASE_HOST=database 
    ports:
      - 5000:5000