version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
           name: Install Dependencies
           command: |
            cd src
            npm install
            cd ../

      # Build Docker images using Docker Compose
      - run:
           name: Build Docker images
           command: |
            docker-compose build

      # Run tests or any other required commands

      - run:
           name: Run Tests
           command: |
            npm test

  # Add more jobs as needed, for example, for deployment

# Workflows define the order of execution
workflows:
  version: 2
  build:
    jobs:
      - build   