version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:21.7.1  
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io
      - run:
          name: Build and Run Docker Compose
          command: |
            docker-compose -f docker-compose.yml up -d
      - run:
          name: Check Docker Daemon Status
          command: docker info



workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only:
                - main
                - develop
