version: 2.1

jobs:
  build:
    docker:
      - image: node:latest

    working_directory: /app

    steps:
      - checkout


      - run:
           name: Install Dependencies
           command: |
            cd src
            npm install
            cd ../

      # Build Docker images using Docker Compose
      - run:
           name: Build Docker images
           command: |
            docker-compose build

      # Run tests or any other required commands

      - run:
           name: Run Tests
           command: |
            npm test

  # Add more jobs as needed, for example, for deployment

# Workflows define the order of execution
workflows:
  version: 2
  build:
    jobs:
      - build