version: 2.1
orbs:
  node: circleci/node@4.7.0
jobs:
  build:
    working_directory: ~/swe-pioneers
    docker:
      - image: cimg/node:lts
    steps:
      - checkout:
        path: ~/swe-pioneers/src
      - run: npm install