version: 2.1
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic-curl
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build container
          command: docker-compose build
      - run:
          name: Run container
          command: docker-compose up -d
  
  test:
    docker:
      - image: cimg/node:21.7.1
    working_directory: ~/project/src
    steps:
      - checkout
      - run:
          name: Current Directory
          command: |
            cd src
            npm install
      - run:
          name: Test City Router
          command: |
            cd src
            npx jest

  test-duplicate-code:
      docker:
        - image: cimg/node:21.7.1
      working_directory: ~/project/src
      steps:
        - checkout
        - run:
           name: Check for Duplicate Code
           command: pwd

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
      - test-duplicate-code
