name: Docker Compose Up

on:
  push:
    branches:
      - main
      - develop
  
jobs:
  docker_compose_up:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Docker Compose
        run: docker-compose up -d
